services:
  broker:
    image: docker.io/library/redis:8
    restart: unless-stopped
    volumes:
    - /opt/docker/appdata/paperless-ngx/redis:/data
  paperless-ai:
    container_name: paperless-ai
    network_mode: bridge
    volumes:
    - /opt/docker/appdata/paperless-ngx/paperless-ai/paperless-ai:/app/data
    ports:
    - 1012:3000
    restart: unless-stopped
    image: clusterzx/paperless-ai
  paperless-gpt:
    image: icereed/paperless-gpt:latest
    environment:
      PAPERLESS_BASE_URL: ${PAPERLESS_NGX_PAPERLESS_GPT_PAPERLESS_BASE_URL:?Set PAPERLESS_NGX_PAPERLESS_GPT_PAPERLESS_BASE_URL}
      PAPERLESS_API_TOKEN: ${PAPERLESS_NGX_PAPERLESS_GPT_PAPERLESS_API_TOKEN:?Set
        PAPERLESS_NGX_PAPERLESS_GPT_PAPERLESS_API_TOKEN}
      PAPERLESS_PUBLIC_URL: ${PAPERLESS_NGX_PAPERLESS_GPT_PAPERLESS_PUBLIC_URL:?Set
        PAPERLESS_NGX_PAPERLESS_GPT_PAPERLESS_PUBLIC_URL}
      MANUAL_TAG: ${PAPERLESS_NGX_PAPERLESS_GPT_MANUAL_TAG:?Set PAPERLESS_NGX_PAPERLESS_GPT_MANUAL_TAG}
      AUTO_TAG: ${PAPERLESS_NGX_PAPERLESS_GPT_AUTO_TAG:?Set PAPERLESS_NGX_PAPERLESS_GPT_AUTO_TAG}
      LLM_PROVIDER: ${PAPERLESS_NGX_PAPERLESS_GPT_LLM_PROVIDER:?Set PAPERLESS_NGX_PAPERLESS_GPT_LLM_PROVIDER}
      LLM_MODEL: ${PAPERLESS_NGX_PAPERLESS_GPT_LLM_MODEL:?Set PAPERLESS_NGX_PAPERLESS_GPT_LLM_MODEL}
      OLLAMA_HOST: ${PAPERLESS_NGX_PAPERLESS_GPT_OLLAMA_HOST:?Set PAPERLESS_NGX_PAPERLESS_GPT_OLLAMA_HOST}
      OLLAMA_CONTEXT_LENGTH: ${PAPERLESS_NGX_PAPERLESS_GPT_OLLAMA_CONTEXT_LENGTH:?Set
        PAPERLESS_NGX_PAPERLESS_GPT_OLLAMA_CONTEXT_LENGTH}
      TOKEN_LIMIT: ${PAPERLESS_NGX_PAPERLESS_GPT_TOKEN_LIMIT:?Set PAPERLESS_NGX_PAPERLESS_GPT_TOKEN_LIMIT}
      OCR_PROVIDER: ${PAPERLESS_NGX_PAPERLESS_GPT_OCR_PROVIDER:?Set PAPERLESS_NGX_PAPERLESS_GPT_OCR_PROVIDER}
      VISION_LLM_PROVIDER: ${PAPERLESS_NGX_PAPERLESS_GPT_VISION_LLM_PROVIDER:?Set
        PAPERLESS_NGX_PAPERLESS_GPT_VISION_LLM_PROVIDER}
      VISION_LLM_MODEL: ${PAPERLESS_NGX_PAPERLESS_GPT_VISION_LLM_MODEL:?Set PAPERLESS_NGX_PAPERLESS_GPT_VISION_LLM_MODEL}
      OCR_PROCESS_MODE: ${PAPERLESS_NGX_PAPERLESS_GPT_OCR_PROCESS_MODE:?Set PAPERLESS_NGX_PAPERLESS_GPT_OCR_PROCESS_MODE}
      PDF_SKIP_EXISTING_OCR: ${PAPERLESS_NGX_PAPERLESS_GPT_PDF_SKIP_EXISTING_OCR:?Set
        PAPERLESS_NGX_PAPERLESS_GPT_PDF_SKIP_EXISTING_OCR}
      CREATE_LOCAL_HOCR: ${PAPERLESS_NGX_PAPERLESS_GPT_CREATE_LOCAL_HOCR:?Set PAPERLESS_NGX_PAPERLESS_GPT_CREATE_LOCAL_HOCR}
      LOCAL_HOCR_PATH: ${PAPERLESS_NGX_PAPERLESS_GPT_LOCAL_HOCR_PATH:?Set PAPERLESS_NGX_PAPERLESS_GPT_LOCAL_HOCR_PATH}
      CREATE_LOCAL_PDF: ${PAPERLESS_NGX_PAPERLESS_GPT_CREATE_LOCAL_PDF:?Set PAPERLESS_NGX_PAPERLESS_GPT_CREATE_LOCAL_PDF}
      LOCAL_PDF_PATH: ${PAPERLESS_NGX_PAPERLESS_GPT_LOCAL_PDF_PATH:?Set PAPERLESS_NGX_PAPERLESS_GPT_LOCAL_PDF_PATH}
      PDF_UPLOAD: ${PAPERLESS_NGX_PAPERLESS_GPT_PDF_UPLOAD:?Set PAPERLESS_NGX_PAPERLESS_GPT_PDF_UPLOAD}
      PDF_REPLACE: ${PAPERLESS_NGX_PAPERLESS_GPT_PDF_REPLACE:?Set PAPERLESS_NGX_PAPERLESS_GPT_PDF_REPLACE}
      PDF_COPY_METADATA: ${PAPERLESS_NGX_PAPERLESS_GPT_PDF_COPY_METADATA:?Set PAPERLESS_NGX_PAPERLESS_GPT_PDF_COPY_METADATA}
      PDF_OCR_TAGGING: ${PAPERLESS_NGX_PAPERLESS_GPT_PDF_OCR_TAGGING:?Set PAPERLESS_NGX_PAPERLESS_GPT_PDF_OCR_TAGGING}
      PDF_OCR_COMPLETE_TAG: ${PAPERLESS_NGX_PAPERLESS_GPT_PDF_OCR_COMPLETE_TAG:?Set
        PAPERLESS_NGX_PAPERLESS_GPT_PDF_OCR_COMPLETE_TAG}
      AUTO_OCR_TAG: ${PAPERLESS_NGX_PAPERLESS_GPT_AUTO_OCR_TAG:?Set PAPERLESS_NGX_PAPERLESS_GPT_AUTO_OCR_TAG}
      OCR_LIMIT_PAGES: ${PAPERLESS_NGX_PAPERLESS_GPT_OCR_LIMIT_PAGES:?Set PAPERLESS_NGX_PAPERLESS_GPT_OCR_LIMIT_PAGES}
      LOG_LEVEL: ${PAPERLESS_NGX_PAPERLESS_GPT_LOG_LEVEL:?Set PAPERLESS_NGX_PAPERLESS_GPT_LOG_LEVEL}
    volumes:
    - /opt/docker/appdata/paperless-ngx/paperless-ai/prompts:/app/prompts
    - /opt/docker/appdata/paperless-ngx/paperless-ai/hocr:/app/hocr
    - /opt/docker/appdata/paperless-ngx/paperless-ai/pdf:/app/pdf
    ports:
    - 1030:8080
    restart: unless-stopped
  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
    - broker
    ports:
    - 1007:8000
    volumes:
    - /opt/docker/appdata/paperless-ngx/data:/usr/src/paperless/data
    - /opt/docker/appdata/paperless-ngx/media:/usr/src/paperless/media
    - /opt/docker/appdata/paperless-ngx/data/export:/usr/src/paperless/export
    - /opt/docker/appdata/paperless-ngx/data/consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: ${PAPERLESS_NGX_WEBSERVER_PAPERLESS_REDIS:?Set PAPERLESS_NGX_WEBSERVER_PAPERLESS_REDIS}
networks: {}
