services:
  backend:
    image: ghcr.io/hillaliy/languard-backend:latest
    container_name: languard-backend
    privileged: true
    network_mode: host
    restart: unless-stopped
    volumes:
    - /opt/docker/appdata/languard/database:/data
    - /opt/docker/appdata/languard/static:/static
    environment:
      SECRET_KEY: ${LANGUARD_BACKEND_SECRET_KEY:?Set LANGUARD_BACKEND_SECRET_KEY}
      ALLOWED_HOSTS: ${LANGUARD_BACKEND_ALLOWED_HOSTS:?Set LANGUARD_BACKEND_ALLOWED_HOSTS}
      BACKEND_LISTEN_PORT: ${LANGUARD_BACKEND_BACKEND_LISTEN_PORT:?Set LANGUARD_BACKEND_BACKEND_LISTEN_PORT}
  scanner:
    image: ghcr.io/hillaliy/languard-scheduler:latest
    container_name: languard-scanner
    privileged: true
    network_mode: host
    command:
    - ${LANGUARD_SCANNER_COMMAND_0:?Set LANGUARD_SCANNER_COMMAND_0}
    - ${LANGUARD_SCANNER_COMMAND_1:?Set LANGUARD_SCANNER_COMMAND_1}
    - ${LANGUARD_SCANNER_COMMAND_2:?Set LANGUARD_SCANNER_COMMAND_2}
    - ${LANGUARD_SCANNER_COMMAND_3:?Set LANGUARD_SCANNER_COMMAND_3}
    - ${LANGUARD_SCANNER_COMMAND_4:?Set LANGUARD_SCANNER_COMMAND_4}
    restart: unless-stopped
    depends_on:
    - backend
    volumes:
    - /opt/docker/appdata/languard/database:/data
    - /opt/docker/appdata/languard/static:/static
    environment:
      SECRET_KEY: ${LANGUARD_SCANNER_SECRET_KEY:?Set LANGUARD_SCANNER_SECRET_KEY}
      ALLOWED_HOSTS: ${LANGUARD_SCANNER_ALLOWED_HOSTS:?Set LANGUARD_SCANNER_ALLOWED_HOSTS}
  frontend:
    image: ghcr.io/hillaliy/languard-frontend:latest
    container_name: languard-frontend
    network_mode: host
    restart: unless-stopped
    depends_on:
    - backend
    environment:
      BACKEND_UPSTREAM: ${LANGUARD_FRONTEND_BACKEND_UPSTREAM:?Set LANGUARD_FRONTEND_BACKEND_UPSTREAM}
      FRONTEND_LISTEN_ADDRESS: ${LANGUARD_FRONTEND_FRONTEND_LISTEN_ADDRESS:?Set LANGUARD_FRONTEND_FRONTEND_LISTEN_ADDRESS}
