services:
  homebox:
    container_name: homebox
    restart: unless-stopped
    ports:
    - 3100:7745
    environment:
      TZ: ${HOMEBOX_HOMEBOX_TZ:?Set HOMEBOX_HOMEBOX_TZ}
      HBOX_AUTH_API_KEY_PEPPER: ${HOMEBOX_HOMEBOX_HBOX_AUTH_API_KEY_PEPPER:?Set HOMEBOX_HOMEBOX_HBOX_AUTH_API_KEY_PEPPER}
    volumes:
    - /opt/docker/appdata/homebox:/data
    image: ghcr.io/sysadminsmedia/homebox:latest
