services:
  connector:
    sysctls:
    - net.ipv4.ping_group_range=0 2147483647
    environment:
      TWINGATE_NETWORK: ${TWINGATE_CONNECTOR_TWINGATE_NETWORK:?Set TWINGATE_CONNECTOR_TWINGATE_NETWORK}
      TWINGATE_ACCESS_TOKEN: ${TWINGATE_CONNECTOR_TWINGATE_ACCESS_TOKEN:?Set TWINGATE_CONNECTOR_TWINGATE_ACCESS_TOKEN}
      TWINGATE_REFRESH_TOKEN: ${TWINGATE_CONNECTOR_TWINGATE_REFRESH_TOKEN:?Set TWINGATE_CONNECTOR_TWINGATE_REFRESH_TOKEN}
      TWINGATE_LABEL_HOSTNAME: ${TWINGATE_CONNECTOR_TWINGATE_LABEL_HOSTNAME:?Set TWINGATE_CONNECTOR_TWINGATE_LABEL_HOSTNAME}
      TWINGATE_LABEL_DEPLOYED_BY: ${TWINGATE_CONNECTOR_TWINGATE_LABEL_DEPLOYED_BY:?Set
        TWINGATE_CONNECTOR_TWINGATE_LABEL_DEPLOYED_BY}
    container_name: twingate-heavenly-swan
    restart: unless-stopped
    pull_policy: always
    image: twingate/connector:1
