services:
  telecloud-go:
    container_name: telecloud
    restart: unless-stopped
    image: ghcr.io/dabeecao/telecloud-go
    ports:
    - 192.168.1.10:1158:8091
    volumes:
    - telecloud-data:/app/data
    user: 65532:65532
    environment:
      API_ID: ${TELECLOUD_TELECLOUD_GO_API_ID:?Set TELECLOUD_TELECLOUD_GO_API_ID}
      API_HASH: ${TELECLOUD_TELECLOUD_GO_API_HASH:?Set TELECLOUD_TELECLOUD_GO_API_HASH}
      LOG_GROUP_ID: ${TELECLOUD_TELECLOUD_GO_LOG_GROUP_ID:?Set TELECLOUD_TELECLOUD_GO_LOG_GROUP_ID}
      PORT: ${TELECLOUD_TELECLOUD_GO_PORT:?Set TELECLOUD_TELECLOUD_GO_PORT}
      DATABASE_PATH: ${TELECLOUD_TELECLOUD_GO_DATABASE_PATH:?Set TELECLOUD_TELECLOUD_GO_DATABASE_PATH}
      THUMBS_DIR: ${TELECLOUD_TELECLOUD_GO_THUMBS_DIR:?Set TELECLOUD_TELECLOUD_GO_THUMBS_DIR}
      TEMP_DIR: ${TELECLOUD_TELECLOUD_GO_TEMP_DIR:?Set TELECLOUD_TELECLOUD_GO_TEMP_DIR}
      SESSION_FILE: ${TELECLOUD_TELECLOUD_GO_SESSION_FILE:?Set TELECLOUD_TELECLOUD_GO_SESSION_FILE}
      FFMPEG_PATH: ${TELECLOUD_TELECLOUD_GO_FFMPEG_PATH:?Set TELECLOUD_TELECLOUD_GO_FFMPEG_PATH}
      YTDLP_PATH: ${TELECLOUD_TELECLOUD_GO_YTDLP_PATH:?Set TELECLOUD_TELECLOUD_GO_YTDLP_PATH}
volumes:
  telecloud-data: null
