services:
  aliasvault:
    image: ghcr.io/aliasvault/aliasvault:latest
    container_name: aliasvault
    restart: unless-stopped
    ports:
    - 2003:80
    - 2004:443
    - '2005:25'
    - 587:587
    volumes:
    - /opt/docker/appdata/aliasvault/database:/database
    - /opt/docker/appdata/aliasvault/logs:/logs
    - /opt/docker/appdata/aliasvault/secrets:/secrets
    - /opt/docker/appdata/aliasvault/certificates:/certificates
    environment:
      HOSTNAME: ${ALIASVAULT_ALIASVAULT_HOSTNAME:?Set ALIASVAULT_ALIASVAULT_HOSTNAME}
      PUBLIC_REGISTRATION_ENABLED: ${ALIASVAULT_ALIASVAULT_PUBLIC_REGISTRATION_ENABLED:?Set
        ALIASVAULT_ALIASVAULT_PUBLIC_REGISTRATION_ENABLED}
      IP_LOGGING_ENABLED: ${ALIASVAULT_ALIASVAULT_IP_LOGGING_ENABLED:?Set ALIASVAULT_ALIASVAULT_IP_LOGGING_ENABLED}
      FORCE_HTTPS_REDIRECT: ${ALIASVAULT_ALIASVAULT_FORCE_HTTPS_REDIRECT:?Set ALIASVAULT_ALIASVAULT_FORCE_HTTPS_REDIRECT}
      SUPPORT_EMAIL: ${ALIASVAULT_ALIASVAULT_SUPPORT_EMAIL:?Set ALIASVAULT_ALIASVAULT_SUPPORT_EMAIL}
      PRIVATE_EMAIL_DOMAINS: ${ALIASVAULT_ALIASVAULT_PRIVATE_EMAIL_DOMAINS:?Set ALIASVAULT_ALIASVAULT_PRIVATE_EMAIL_DOMAINS}
      SMTP_TLS_ENABLED: ${ALIASVAULT_ALIASVAULT_SMTP_TLS_ENABLED:?Set ALIASVAULT_ALIASVAULT_SMTP_TLS_ENABLED}
