name: ports
services:
  ports:
    image: ghcr.io/palermostest25/ports:latest
    container_name: ports
    restart: unless-stopped
    user: 0:0
    environment:
      PORT_RANGES: ${PORTS_PORTS_PORT_RANGES:?Set PORTS_PORTS_PORT_RANGES}
      RESERVED_PORTS: ${PORTS_PORTS_RESERVED_PORTS:?Set PORTS_PORTS_RESERVED_PORTS}
      HTTPS_PORTS: ${PORTS_PORTS_HTTPS_PORTS:?Set PORTS_PORTS_HTTPS_PORTS}
      AVAILABLE_COUNT: ${PORTS_PORTS_AVAILABLE_COUNT:?Set PORTS_PORTS_AVAILABLE_COUNT}
      SHOW_ALL_CONTAINERS: ${PORTS_PORTS_SHOW_ALL_CONTAINERS:?Set PORTS_PORTS_SHOW_ALL_CONTAINERS}
      CHECK_HOST_BIND: ${PORTS_PORTS_CHECK_HOST_BIND:?Set PORTS_PORTS_CHECK_HOST_BIND}
    ports:
    - 1100:5000
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    read_only: true
    tmpfs:
    - /tmp
    security_opt:
    - no-new-privileges:true
    cap_drop:
    - ALL
