services:
  grafana-enterprise:
    container_name: grafana
    restart: always
    ports:
    - 1005:3000
    image: grafana/grafana-enterprise
    environment:
      GF_AUTH_LOGIN_MAXIMUM_INACTIVE_LIFETIME_DURATION: ${GRAFANA_GRAFANA_ENTERPRISE_GF_AUTH_LOGIN_MAXIMUM_INACTIVE_LIFETIME_DURATION:?Set
        GRAFANA_GRAFANA_ENTERPRISE_GF_AUTH_LOGIN_MAXIMUM_INACTIVE_LIFETIME_DURATION}
      GF_AUTH_LOGIN_MAXIMUM_LIFETIME_DURATION: ${GRAFANA_GRAFANA_ENTERPRISE_GF_AUTH_LOGIN_MAXIMUM_LIFETIME_DURATION:?Set
        GRAFANA_GRAFANA_ENTERPRISE_GF_AUTH_LOGIN_MAXIMUM_LIFETIME_DURATION}
    volumes:
    - /opt/docker/appdata/grafana:/var/lib/grafana
networks: {}
