services:
  cronmaster:
    image: ghcr.io/fccview/cronmaster:main
    ports:
    - 1011:3000
    environment:
      NODE_ENV: ${CRONMASTER_CRONMASTER_NODE_ENV:?Set CRONMASTER_CRONMASTER_NODE_ENV}
      DOCKER: ${CRONMASTER_CRONMASTER_DOCKER:?Set CRONMASTER_CRONMASTER_DOCKER}
      NEXT_PUBLIC_CLOCK_UPDATE_INTERVAL: ${CRONMASTER_CRONMASTER_NEXT_PUBLIC_CLOCK_UPDATE_INTERVAL:?Set
        CRONMASTER_CRONMASTER_NEXT_PUBLIC_CLOCK_UPDATE_INTERVAL}
      NEXT_PUBLIC_HOST_PROJECT_DIR: ${CRONMASTER_CRONMASTER_NEXT_PUBLIC_HOST_PROJECT_DIR:?Set
        CRONMASTER_CRONMASTER_NEXT_PUBLIC_HOST_PROJECT_DIR}
    volumes:
    - /var/spool/cron/crontabs:/host/cron/crontabs
    - /etc/crontab:/host/crontab:ro
    - /proc:/host/proc:ro
    - /sys:/host/sys:ro
    - /etc:/host/etc:ro
    - /usr:/host/usr:ro
    - /opt/docker/appdata/cronmaster/scripts:/app/scripts
    - /opt/docker/appdata/cronmaster/data:/app/data
    - /opt/docker/appdata/cronmaster/snippets:/app/snippets
    restart: unless-stopped
