services:
  bytestash:
    image: ghcr.io/jordan-dalby/bytestash:latest
    restart: always
    volumes:
    - /opt/docker/appdata/snippets:/data/snippets
    ports:
    - 1070:5000
    environment:
      BASE_PATH: ${BYTESTASH_BYTESTASH_BASE_PATH?Set BYTESTASH_BYTESTASH_BASE_PATH}
      JWT_SECRET: ${BYTESTASH_BYTESTASH_JWT_SECRET:?Set BYTESTASH_BYTESTASH_JWT_SECRET}
      TOKEN_EXPIRY: ${BYTESTASH_BYTESTASH_TOKEN_EXPIRY:?Set BYTESTASH_BYTESTASH_TOKEN_EXPIRY}
      ALLOW_NEW_ACCOUNTS: ${BYTESTASH_BYTESTASH_ALLOW_NEW_ACCOUNTS:?Set BYTESTASH_BYTESTASH_ALLOW_NEW_ACCOUNTS}
      DEBUG: ${BYTESTASH_BYTESTASH_DEBUG:?Set BYTESTASH_BYTESTASH_DEBUG}
      DISABLE_ACCOUNTS: ${BYTESTASH_BYTESTASH_DISABLE_ACCOUNTS:?Set BYTESTASH_BYTESTASH_DISABLE_ACCOUNTS}
      DISABLE_INTERNAL_ACCOUNTS: ${BYTESTASH_BYTESTASH_DISABLE_INTERNAL_ACCOUNTS:?Set
        BYTESTASH_BYTESTASH_DISABLE_INTERNAL_ACCOUNTS}
      OIDC_ENABLED: ${BYTESTASH_BYTESTASH_OIDC_ENABLED:?Set BYTESTASH_BYTESTASH_OIDC_ENABLED}
      OIDC_DISPLAY_NAME: ${BYTESTASH_BYTESTASH_OIDC_DISPLAY_NAME?Set BYTESTASH_BYTESTASH_OIDC_DISPLAY_NAME}
      OIDC_ISSUER_URL: ${BYTESTASH_BYTESTASH_OIDC_ISSUER_URL?Set BYTESTASH_BYTESTASH_OIDC_ISSUER_URL}
      OIDC_CLIENT_ID: ${BYTESTASH_BYTESTASH_OIDC_CLIENT_ID?Set BYTESTASH_BYTESTASH_OIDC_CLIENT_ID}
      OIDC_CLIENT_SECRET: ${BYTESTASH_BYTESTASH_OIDC_CLIENT_SECRET?Set BYTESTASH_BYTESTASH_OIDC_CLIENT_SECRET}
      OIDC_SCOPES: ${BYTESTASH_BYTESTASH_OIDC_SCOPES?Set BYTESTASH_BYTESTASH_OIDC_SCOPES}
