services:
  couchdb-obsidian-livesync:
    image: docker.io/oleduc/docker-obsidian-livesync-couchdb:master
    restart: always
    environment:
      SERVER_URL: ${OBSIDIAN_LIVESYNC_COUCHDB_OBSIDIAN_LIVESYNC_SERVER_URL:?Set OBSIDIAN_LIVESYNC_COUCHDB_OBSIDIAN_LIVESYNC_SERVER_URL}
      COUCHDB_USER: ${OBSIDIAN_LIVESYNC_COUCHDB_OBSIDIAN_LIVESYNC_COUCHDB_USER:?Set
        OBSIDIAN_LIVESYNC_COUCHDB_OBSIDIAN_LIVESYNC_COUCHDB_USER}
      COUCHDB_PASSWORD: ${OBSIDIAN_LIVESYNC_COUCHDB_OBSIDIAN_LIVESYNC_COUCHDB_PASSWORD:?Set
        OBSIDIAN_LIVESYNC_COUCHDB_OBSIDIAN_LIVESYNC_COUCHDB_PASSWORD}
      COUCHDB_DATABASE: ${OBSIDIAN_LIVESYNC_COUCHDB_OBSIDIAN_LIVESYNC_COUCHDB_DATABASE:?Set
        OBSIDIAN_LIVESYNC_COUCHDB_OBSIDIAN_LIVESYNC_COUCHDB_DATABASE}
    ports:
    - 5984:5984
    volumes:
    - /opt/docker/appdata/obsidian-livesync:/opt/couchdb/data
