services:
  convertx:
    image: ghcr.io/c4illin/convertx
    restart: always
    volumes:
    - /opt/docker/appdata/convertx:/app/data
    environment:
      ACCOUNT_REGISTRATION: ${CONVERTX_CONVERTX_ACCOUNT_REGISTRATION:?Set CONVERTX_CONVERTX_ACCOUNT_REGISTRATION}
      JWT_SECRET: ${CONVERTX_CONVERTX_JWT_SECRET:?Set CONVERTX_CONVERTX_JWT_SECRET}
      HTTP_ALLOWED: ${CONVERTX_CONVERTX_HTTP_ALLOWED:?Set CONVERTX_CONVERTX_HTTP_ALLOWED}
      ALLOW_UNAUTHENTICATED: ${CONVERTX_CONVERTX_ALLOW_UNAUTHENTICATED:?Set CONVERTX_CONVERTX_ALLOW_UNAUTHENTICATED}
      AUTO_DELETE_EVERY_N_HOURS: ${CONVERTX_CONVERTX_AUTO_DELETE_EVERY_N_HOURS:?Set
        CONVERTX_CONVERTX_AUTO_DELETE_EVERY_N_HOURS}
    ports:
    - 4010:3000
