services:
  bookstack:
    image: lscr.io/linuxserver/bookstack:version-v26.03.3
    container_name: bookstack
    ports:
    - 192.168.1.10:1355:80
    volumes:
    - /opt/docker/appdata/bookstack/app:/config
    restart: unless-stopped
    depends_on:
    - mariadb
    environment:
      PUID: ${BOOKSTACK_BOOKSTACK_PUID:?Set BOOKSTACK_BOOKSTACK_PUID}
      PGID: ${BOOKSTACK_BOOKSTACK_PGID:?Set BOOKSTACK_BOOKSTACK_PGID}
      TZ: ${BOOKSTACK_BOOKSTACK_TZ:?Set BOOKSTACK_BOOKSTACK_TZ}
      APP_URL: ${BOOKSTACK_BOOKSTACK_APP_URL:?Set BOOKSTACK_BOOKSTACK_APP_URL}
      APP_KEY: ${BOOKSTACK_BOOKSTACK_APP_KEY:?Set BOOKSTACK_BOOKSTACK_APP_KEY}
      DB_HOST: ${BOOKSTACK_BOOKSTACK_DB_HOST:?Set BOOKSTACK_BOOKSTACK_DB_HOST}
      DB_PORT: ${BOOKSTACK_BOOKSTACK_DB_PORT:?Set BOOKSTACK_BOOKSTACK_DB_PORT}
      DB_DATABASE: ${BOOKSTACK_BOOKSTACK_DB_DATABASE:?Set BOOKSTACK_BOOKSTACK_DB_DATABASE}
      DB_USERNAME: ${BOOKSTACK_BOOKSTACK_DB_USERNAME:?Set BOOKSTACK_BOOKSTACK_DB_USERNAME}
      DB_PASSWORD: ${BOOKSTACK_BOOKSTACK_DB_PASSWORD:?Set BOOKSTACK_BOOKSTACK_DB_PASSWORD}
  mariadb:
    image: lscr.io/linuxserver/mariadb:11.4.9
    container_name: bookstack_mariadb
    volumes:
    - /opt/docker/appdata/bookstack/db:/config
    restart: unless-stopped
    environment:
      PUID: ${BOOKSTACK_MARIADB_PUID:?Set BOOKSTACK_MARIADB_PUID}
      PGID: ${BOOKSTACK_MARIADB_PGID:?Set BOOKSTACK_MARIADB_PGID}
      TZ: ${BOOKSTACK_MARIADB_TZ:?Set BOOKSTACK_MARIADB_TZ}
      MYSQL_ROOT_PASSWORD: ${BOOKSTACK_MARIADB_MYSQL_ROOT_PASSWORD:?Set BOOKSTACK_MARIADB_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${BOOKSTACK_MARIADB_MYSQL_DATABASE:?Set BOOKSTACK_MARIADB_MYSQL_DATABASE}
      MYSQL_USER: ${BOOKSTACK_MARIADB_MYSQL_USER:?Set BOOKSTACK_MARIADB_MYSQL_USER}
      MYSQL_PASSWORD: ${BOOKSTACK_MARIADB_MYSQL_PASSWORD:?Set BOOKSTACK_MARIADB_MYSQL_PASSWORD}
