services:
  outline:
    image: docker.getoutline.com/outlinewiki/outline:latest
    ports:
    - 192.168.1.10:1354:3000
    volumes:
    - /opt/docker/appdata/outline/storage:/var/lib/outline/data
    depends_on:
    - postgres
    - redis
    restart: unless-stopped
    environment:
      NODE_ENV: ${OUTLINE_OUTLINE_NODE_ENV:?Set OUTLINE_OUTLINE_NODE_ENV}
      URL: ${OUTLINE_OUTLINE_URL:?Set OUTLINE_OUTLINE_URL}
      PORT: ${OUTLINE_OUTLINE_PORT:?Set OUTLINE_OUTLINE_PORT}
      COLLABORATION_URL: ${OUTLINE_OUTLINE_COLLABORATION_URL:?Set OUTLINE_OUTLINE_COLLABORATION_URL}
      CDN_URL: ${OUTLINE_OUTLINE_CDN_URL:?Set OUTLINE_OUTLINE_CDN_URL}
      WEB_CONCURRENCY: ${OUTLINE_OUTLINE_WEB_CONCURRENCY:?Set OUTLINE_OUTLINE_WEB_CONCURRENCY}
      SECRET_KEY: ${OUTLINE_OUTLINE_SECRET_KEY:?Set OUTLINE_OUTLINE_SECRET_KEY}
      UTILS_SECRET: ${OUTLINE_OUTLINE_UTILS_SECRET:?Set OUTLINE_OUTLINE_UTILS_SECRET}
      DEFAULT_LANGUAGE: ${OUTLINE_OUTLINE_DEFAULT_LANGUAGE:?Set OUTLINE_OUTLINE_DEFAULT_LANGUAGE}
      DATABASE_URL: ${OUTLINE_OUTLINE_DATABASE_URL:?Set OUTLINE_OUTLINE_DATABASE_URL}
      DATABASE_CONNECTION_POOL_MIN: ${OUTLINE_OUTLINE_DATABASE_CONNECTION_POOL_MIN:?Set
        OUTLINE_OUTLINE_DATABASE_CONNECTION_POOL_MIN}
      DATABASE_CONNECTION_POOL_MAX: ${OUTLINE_OUTLINE_DATABASE_CONNECTION_POOL_MAX:?Set
        OUTLINE_OUTLINE_DATABASE_CONNECTION_POOL_MAX}
      REDIS_URL: ${OUTLINE_OUTLINE_REDIS_URL:?Set OUTLINE_OUTLINE_REDIS_URL}
      REDIS_COLLABORATION_URL: ${OUTLINE_OUTLINE_REDIS_COLLABORATION_URL:?Set OUTLINE_OUTLINE_REDIS_COLLABORATION_URL}
      FILE_STORAGE: ${OUTLINE_OUTLINE_FILE_STORAGE:?Set OUTLINE_OUTLINE_FILE_STORAGE}
      FILE_STORAGE_LOCAL_ROOT_DIR: ${OUTLINE_OUTLINE_FILE_STORAGE_LOCAL_ROOT_DIR:?Set
        OUTLINE_OUTLINE_FILE_STORAGE_LOCAL_ROOT_DIR}
      FILE_STORAGE_UPLOAD_MAX_SIZE: ${OUTLINE_OUTLINE_FILE_STORAGE_UPLOAD_MAX_SIZE:?Set
        OUTLINE_OUTLINE_FILE_STORAGE_UPLOAD_MAX_SIZE}
      FILE_STORAGE_IMPORT_MAX_SIZE: ${OUTLINE_OUTLINE_FILE_STORAGE_IMPORT_MAX_SIZE:?Set
        OUTLINE_OUTLINE_FILE_STORAGE_IMPORT_MAX_SIZE}
      FILE_STORAGE_WORKSPACE_IMPORT_MAX_SIZE: ${OUTLINE_OUTLINE_FILE_STORAGE_WORKSPACE_IMPORT_MAX_SIZE:?Set
        OUTLINE_OUTLINE_FILE_STORAGE_WORKSPACE_IMPORT_MAX_SIZE}
      AWS_ACCESS_KEY_ID: ${OUTLINE_OUTLINE_AWS_ACCESS_KEY_ID:?Set OUTLINE_OUTLINE_AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${OUTLINE_OUTLINE_AWS_SECRET_ACCESS_KEY:?Set OUTLINE_OUTLINE_AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${OUTLINE_OUTLINE_AWS_REGION:?Set OUTLINE_OUTLINE_AWS_REGION}
      AWS_S3_ACCELERATE_URL: ${OUTLINE_OUTLINE_AWS_S3_ACCELERATE_URL:?Set OUTLINE_OUTLINE_AWS_S3_ACCELERATE_URL}
      AWS_S3_UPLOAD_BUCKET_URL: ${OUTLINE_OUTLINE_AWS_S3_UPLOAD_BUCKET_URL:?Set OUTLINE_OUTLINE_AWS_S3_UPLOAD_BUCKET_URL}
      AWS_S3_UPLOAD_BUCKET_NAME: ${OUTLINE_OUTLINE_AWS_S3_UPLOAD_BUCKET_NAME:?Set
        OUTLINE_OUTLINE_AWS_S3_UPLOAD_BUCKET_NAME}
      AWS_S3_FORCE_PATH_STYLE: ${OUTLINE_OUTLINE_AWS_S3_FORCE_PATH_STYLE:?Set OUTLINE_OUTLINE_AWS_S3_FORCE_PATH_STYLE}
      AWS_S3_ACL: ${OUTLINE_OUTLINE_AWS_S3_ACL:?Set OUTLINE_OUTLINE_AWS_S3_ACL}
      SSL_KEY: ${OUTLINE_OUTLINE_SSL_KEY:?Set OUTLINE_OUTLINE_SSL_KEY}
      SSL_CERT: ${OUTLINE_OUTLINE_SSL_CERT:?Set OUTLINE_OUTLINE_SSL_CERT}
      FORCE_HTTPS: ${OUTLINE_OUTLINE_FORCE_HTTPS:?Set OUTLINE_OUTLINE_FORCE_HTTPS}
      SLACK_CLIENT_ID: ${OUTLINE_OUTLINE_SLACK_CLIENT_ID:?Set OUTLINE_OUTLINE_SLACK_CLIENT_ID}
      SLACK_CLIENT_SECRET: ${OUTLINE_OUTLINE_SLACK_CLIENT_SECRET:?Set OUTLINE_OUTLINE_SLACK_CLIENT_SECRET}
      GOOGLE_CLIENT_ID: ${OUTLINE_OUTLINE_GOOGLE_CLIENT_ID:?Set OUTLINE_OUTLINE_GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${OUTLINE_OUTLINE_GOOGLE_CLIENT_SECRET:?Set OUTLINE_OUTLINE_GOOGLE_CLIENT_SECRET}
      AZURE_CLIENT_ID: ${OUTLINE_OUTLINE_AZURE_CLIENT_ID:?Set OUTLINE_OUTLINE_AZURE_CLIENT_ID}
      AZURE_CLIENT_SECRET: ${OUTLINE_OUTLINE_AZURE_CLIENT_SECRET:?Set OUTLINE_OUTLINE_AZURE_CLIENT_SECRET}
      AZURE_RESOURCE_APP_ID: ${OUTLINE_OUTLINE_AZURE_RESOURCE_APP_ID:?Set OUTLINE_OUTLINE_AZURE_RESOURCE_APP_ID}
      DISCORD_CLIENT_ID: ${OUTLINE_OUTLINE_DISCORD_CLIENT_ID:?Set OUTLINE_OUTLINE_DISCORD_CLIENT_ID}
      DISCORD_CLIENT_SECRET: ${OUTLINE_OUTLINE_DISCORD_CLIENT_SECRET:?Set OUTLINE_OUTLINE_DISCORD_CLIENT_SECRET}
      DISCORD_SERVER_ID: ${OUTLINE_OUTLINE_DISCORD_SERVER_ID:?Set OUTLINE_OUTLINE_DISCORD_SERVER_ID}
      DISCORD_SERVER_ROLES: ${OUTLINE_OUTLINE_DISCORD_SERVER_ROLES:?Set OUTLINE_OUTLINE_DISCORD_SERVER_ROLES}
      OIDC_CLIENT_ID: ${OUTLINE_OUTLINE_OIDC_CLIENT_ID:?Set OUTLINE_OUTLINE_OIDC_CLIENT_ID}
      OIDC_CLIENT_SECRET: ${OUTLINE_OUTLINE_OIDC_CLIENT_SECRET:?Set OUTLINE_OUTLINE_OIDC_CLIENT_SECRET}
      OIDC_AUTH_URI: ${OUTLINE_OUTLINE_OIDC_AUTH_URI:?Set OUTLINE_OUTLINE_OIDC_AUTH_URI}
      OIDC_TOKEN_URI: ${OUTLINE_OUTLINE_OIDC_TOKEN_URI:?Set OUTLINE_OUTLINE_OIDC_TOKEN_URI}
      OIDC_USERINFO_URI: ${OUTLINE_OUTLINE_OIDC_USERINFO_URI:?Set OUTLINE_OUTLINE_OIDC_USERINFO_URI}
      OIDC_LOGOUT_URI: ${OUTLINE_OUTLINE_OIDC_LOGOUT_URI:?Set OUTLINE_OUTLINE_OIDC_LOGOUT_URI}
      OIDC_USERNAME_CLAIM: ${OUTLINE_OUTLINE_OIDC_USERNAME_CLAIM:?Set OUTLINE_OUTLINE_OIDC_USERNAME_CLAIM}
      OIDC_DISPLAY_NAME: ${OUTLINE_OUTLINE_OIDC_DISPLAY_NAME:?Set OUTLINE_OUTLINE_OIDC_DISPLAY_NAME}
      OIDC_SCOPES: ${OUTLINE_OUTLINE_OIDC_SCOPES:?Set OUTLINE_OUTLINE_OIDC_SCOPES}
      SMTP_SERVICE: ${OUTLINE_OUTLINE_SMTP_SERVICE:?Set OUTLINE_OUTLINE_SMTP_SERVICE}
      SMTP_USERNAME: ${OUTLINE_OUTLINE_SMTP_USERNAME:?Set OUTLINE_OUTLINE_SMTP_USERNAME}
      SMTP_PASSWORD: ${OUTLINE_OUTLINE_SMTP_PASSWORD:?Set OUTLINE_OUTLINE_SMTP_PASSWORD}
      SMTP_FROM_EMAIL: ${OUTLINE_OUTLINE_SMTP_FROM_EMAIL:?Set OUTLINE_OUTLINE_SMTP_FROM_EMAIL}
      RATE_LIMITER_ENABLED: ${OUTLINE_OUTLINE_RATE_LIMITER_ENABLED:?Set OUTLINE_OUTLINE_RATE_LIMITER_ENABLED}
      RATE_LIMITER_REQUESTS: ${OUTLINE_OUTLINE_RATE_LIMITER_REQUESTS:?Set OUTLINE_OUTLINE_RATE_LIMITER_REQUESTS}
      RATE_LIMITER_DURATION_WINDOW: ${OUTLINE_OUTLINE_RATE_LIMITER_DURATION_WINDOW:?Set
        OUTLINE_OUTLINE_RATE_LIMITER_DURATION_WINDOW}
      RATE_LIMITER_MULTIPLIER: ${OUTLINE_OUTLINE_RATE_LIMITER_MULTIPLIER:?Set OUTLINE_OUTLINE_RATE_LIMITER_MULTIPLIER}
      GITHUB_CLIENT_ID: ${OUTLINE_OUTLINE_GITHUB_CLIENT_ID:?Set OUTLINE_OUTLINE_GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${OUTLINE_OUTLINE_GITHUB_CLIENT_SECRET:?Set OUTLINE_OUTLINE_GITHUB_CLIENT_SECRET}
      GITHUB_WEBHOOK_SECRET: ${OUTLINE_OUTLINE_GITHUB_WEBHOOK_SECRET:?Set OUTLINE_OUTLINE_GITHUB_WEBHOOK_SECRET}
      GITHUB_APP_NAME: ${OUTLINE_OUTLINE_GITHUB_APP_NAME:?Set OUTLINE_OUTLINE_GITHUB_APP_NAME}
      GITHUB_APP_ID: ${OUTLINE_OUTLINE_GITHUB_APP_ID:?Set OUTLINE_OUTLINE_GITHUB_APP_ID}
      GITHUB_APP_PRIVATE_KEY: ${OUTLINE_OUTLINE_GITHUB_APP_PRIVATE_KEY:?Set OUTLINE_OUTLINE_GITHUB_APP_PRIVATE_KEY}
      GITLAB_CLIENT_ID: ${OUTLINE_OUTLINE_GITLAB_CLIENT_ID:?Set OUTLINE_OUTLINE_GITLAB_CLIENT_ID}
      GITLAB_CLIENT_SECRET: ${OUTLINE_OUTLINE_GITLAB_CLIENT_SECRET:?Set OUTLINE_OUTLINE_GITLAB_CLIENT_SECRET}
      LINEAR_CLIENT_ID: ${OUTLINE_OUTLINE_LINEAR_CLIENT_ID:?Set OUTLINE_OUTLINE_LINEAR_CLIENT_ID}
      LINEAR_CLIENT_SECRET: ${OUTLINE_OUTLINE_LINEAR_CLIENT_SECRET:?Set OUTLINE_OUTLINE_LINEAR_CLIENT_SECRET}
      SLACK_VERIFICATION_TOKEN: ${OUTLINE_OUTLINE_SLACK_VERIFICATION_TOKEN:?Set OUTLINE_OUTLINE_SLACK_VERIFICATION_TOKEN}
      SLACK_APP_ID: ${OUTLINE_OUTLINE_SLACK_APP_ID:?Set OUTLINE_OUTLINE_SLACK_APP_ID}
      SLACK_MESSAGE_ACTIONS: ${OUTLINE_OUTLINE_SLACK_MESSAGE_ACTIONS:?Set OUTLINE_OUTLINE_SLACK_MESSAGE_ACTIONS}
      FIGMA_CLIENT_ID: ${OUTLINE_OUTLINE_FIGMA_CLIENT_ID:?Set OUTLINE_OUTLINE_FIGMA_CLIENT_ID}
      FIGMA_CLIENT_SECRET: ${OUTLINE_OUTLINE_FIGMA_CLIENT_SECRET:?Set OUTLINE_OUTLINE_FIGMA_CLIENT_SECRET}
      DROPBOX_APP_KEY: ${OUTLINE_OUTLINE_DROPBOX_APP_KEY:?Set OUTLINE_OUTLINE_DROPBOX_APP_KEY}
      SENTRY_DSN: ${OUTLINE_OUTLINE_SENTRY_DSN:?Set OUTLINE_OUTLINE_SENTRY_DSN}
      SENTRY_TUNNEL: ${OUTLINE_OUTLINE_SENTRY_TUNNEL:?Set OUTLINE_OUTLINE_SENTRY_TUNNEL}
      NOTION_CLIENT_ID: ${OUTLINE_OUTLINE_NOTION_CLIENT_ID:?Set OUTLINE_OUTLINE_NOTION_CLIENT_ID}
      NOTION_CLIENT_SECRET: ${OUTLINE_OUTLINE_NOTION_CLIENT_SECRET:?Set OUTLINE_OUTLINE_NOTION_CLIENT_SECRET}
      IFRAMELY_URL: ${OUTLINE_OUTLINE_IFRAMELY_URL:?Set OUTLINE_OUTLINE_IFRAMELY_URL}
      IFRAMELY_API_KEY: ${OUTLINE_OUTLINE_IFRAMELY_API_KEY:?Set OUTLINE_OUTLINE_IFRAMELY_API_KEY}
      ENABLE_UPDATES: ${OUTLINE_OUTLINE_ENABLE_UPDATES:?Set OUTLINE_OUTLINE_ENABLE_UPDATES}
      DEBUG: ${OUTLINE_OUTLINE_DEBUG:?Set OUTLINE_OUTLINE_DEBUG}
      LOG_LEVEL: ${OUTLINE_OUTLINE_LOG_LEVEL:?Set OUTLINE_OUTLINE_LOG_LEVEL}
      PGSSLMODE: ${OUTLINE_OUTLINE_PGSSLMODE:?Set OUTLINE_OUTLINE_PGSSLMODE}
  redis:
    image: redis
    ports:
    - 6379:6379
    volumes:
    - /opt/docker/appdata/outline/redis.conf:/redis.conf
    command:
    - ${OUTLINE_REDIS_COMMAND_0:?Set OUTLINE_REDIS_COMMAND_0}
    - ${OUTLINE_REDIS_COMMAND_1:?Set OUTLINE_REDIS_COMMAND_1}
    restart: unless-stopped
  postgres:
    image: postgres:18
    volumes:
    - /opt/docker/appdata/outline/database:/var/lib/postgresql
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${OUTLINE_POSTGRES_POSTGRES_USER:?Set OUTLINE_POSTGRES_POSTGRES_USER}
      POSTGRES_PASSWORD: ${OUTLINE_POSTGRES_POSTGRES_PASSWORD:?Set OUTLINE_POSTGRES_POSTGRES_PASSWORD}
      POSTGRES_DB: ${OUTLINE_POSTGRES_POSTGRES_DB:?Set OUTLINE_POSTGRES_POSTGRES_DB}
networks: {}
